import { Component, OnInit } from '@angular/core';
import { Cliente } from './cliente';

@Component({
  selector: 'app-clientes',
  templateUrl: './clientes.component.html'
})
export class ClientesComponent implements OnInit {

  clientes: Cliente[] = [{
    "id": 1,
    "nome": "Micheil",
    "sobrenome": "Ludgate",
    "email": "mludgate0@cisco.com",
    "createdAt": "2019-10-04"
  }, {
    "id": 2,
    "nome": "Cooper",
    "sobrenome": "Lindsay",
    "email": "clindsay1@amazon.de",
    "createdAt": "2019-11-14"
  }, {
    "id": 3,
    "nome": "Shir",
    "sobrenome": "Goalley",
    "email": "sgoalley2@vk.com",
    "createdAt": "2019-08-26"
  }, {
    "id": 4,
    "nome": "Janeva",
    "sobrenome": "Hollyman",
    "email": "jhollyman3@newsvine.com",
    "createdAt": "2019-11-14"
  }, {
    "id": 5,
    "nome": "Davide",
    "sobrenome": "Brecken",
    "email": "dbrecken4@java.com",
    "createdAt": "2019-08-18"
  }, {
    "id": 6,
    "nome": "Jayne",
    "sobrenome": "MacKeever",
    "email": "jmackeever5@addthis.com",
    "createdAt": "2019-04-30"
  }, {
    "id": 7,
    "nome": "Helen",
    "sobrenome": "Gladtbach",
    "email": "hgladtbach6@altervista.org",
    "createdAt": "2019-04-30"
  }, {
    "id": 8,
    "nome": "Lexis",
    "sobrenome": "Bonome",
    "email": "lbonome7@netvibes.com",
    "createdAt": "2019-05-19"
  }, {
    "id": 9,
    "nome": "Fair",
    "sobrenome": "Sander",
    "email": "fsander8@tamu.edu",
    "createdAt": "2019-11-02"
  }, {
    "id": 10,
    "nome": "Erhard",
    "sobrenome": "Headingham",
    "email": "eheadingham9@ustream.tv",
    "createdAt": "2019-07-07"
  }, {
    "id": 11,
    "nome": "Johna",
    "sobrenome": "Rump",
    "email": "jrumpa@ibm.com",
    "createdAt": "2019-01-20"
  }, {
    "id": 12,
    "nome": "Hendrick",
    "sobrenome": "Flacknoe",
    "email": "hflacknoeb@xrea.com",
    "createdAt": "2019-05-12"
  }, {
    "id": 13,
    "nome": "Bessy",
    "sobrenome": "Strickland",
    "email": "bstricklandc@issuu.com",
    "createdAt": "2019-08-29"
  }, {
    "id": 14,
    "nome": "Bing",
    "sobrenome": "Osmund",
    "email": "bosmundd@amazon.co.jp",
    "createdAt": "2019-04-25"
  }, {
    "id": 15,
    "nome": "Pammie",
    "sobrenome": "De Paepe",
    "email": "pdepaepee@sitemeter.com",
    "createdAt": "2018-11-30"
  }, {
    "id": 16,
    "nome": "Gregoor",
    "sobrenome": "Elstow",
    "email": "gelstowf@ca.gov",
    "createdAt": "2019-08-24"
  }, {
    "id": 17,
    "nome": "Emmie",
    "sobrenome": "Lomasny",
    "email": "elomasnyg@ucoz.com",
    "createdAt": "2019-06-09"
  }, {
    "id": 18,
    "nome": "Eachelle",
    "sobrenome": "Renny",
    "email": "erennyh@army.mil",
    "createdAt": "2019-02-16"
  }, {
    "id": 19,
    "nome": "Nigel",
    "sobrenome": "Sinisbury",
    "email": "nsinisburyi@fc2.com",
    "createdAt": "2019-03-08"
  }, {
    "id": 20,
    "nome": "Lesli",
    "sobrenome": "Nyland",
    "email": "lnylandj@blogs.com",
    "createdAt": "2019-09-09"
  }, {
    "id": 21,
    "nome": "Maryjo",
    "sobrenome": "Grigorian",
    "email": "mgrigoriank@hhs.gov",
    "createdAt": "2019-04-20"
  }, {
    "id": 22,
    "nome": "Marrissa",
    "sobrenome": "Stenett",
    "email": "mstenettl@mtv.com",
    "createdAt": "2019-01-18"
  }, {
    "id": 23,
    "nome": "Starlin",
    "sobrenome": "Challenor",
    "email": "schallenorm@jigsy.com",
    "createdAt": "2019-08-20"
  }, {
    "id": 24,
    "nome": "Bernardine",
    "sobrenome": "Masser",
    "email": "bmassern@sciencedaily.com",
    "createdAt": "2019-08-23"
  }, {
    "id": 25,
    "nome": "Aile",
    "sobrenome": "Toleman",
    "email": "atolemano@wp.com",
    "createdAt": "2019-02-17"
  }, {
    "id": 26,
    "nome": "David",
    "sobrenome": "Clausner",
    "email": "dclausnerp@gmpg.org",
    "createdAt": "2018-12-21"
  }, {
    "id": 27,
    "nome": "Valle",
    "sobrenome": "Gate",
    "email": "vgateq@devhub.com",
    "createdAt": "2019-09-19"
  }, {
    "id": 28,
    "nome": "Brigitta",
    "sobrenome": "Lilie",
    "email": "blilier@soundcloud.com",
    "createdAt": "2019-01-13"
  }, {
    "id": 29,
    "nome": "Vassili",
    "sobrenome": "Tacon",
    "email": "vtacons@tinyurl.com",
    "createdAt": "2019-06-23"
  }, {
    "id": 30,
    "nome": "John",
    "sobrenome": "McKeeman",
    "email": "jmckeemant@usda.gov",
    "createdAt": "2019-04-28"
  }, {
    "id": 31,
    "nome": "Dorothea",
    "sobrenome": "Allbon",
    "email": "dallbonu@blogger.com",
    "createdAt": "2019-05-19"
  }, {
    "id": 32,
    "nome": "Bertie",
    "sobrenome": "Dybald",
    "email": "bdybaldv@yale.edu",
    "createdAt": "2019-11-22"
  }, {
    "id": 33,
    "nome": "Sanderson",
    "sobrenome": "Sargood",
    "email": "ssargoodw@themeforest.net",
    "createdAt": "2019-03-22"
  }, {
    "id": 34,
    "nome": "Daile",
    "sobrenome": "Downing",
    "email": "ddowningx@dell.com",
    "createdAt": "2019-07-20"
  }, {
    "id": 35,
    "nome": "Wallie",
    "sobrenome": "Emney",
    "email": "wemneyy@rakuten.co.jp",
    "createdAt": "2019-05-01"
  }, {
    "id": 36,
    "nome": "Barb",
    "sobrenome": "Buxsey",
    "email": "bbuxseyz@gravatar.com",
    "createdAt": "2019-11-13"
  }, {
    "id": 37,
    "nome": "Victor",
    "sobrenome": "Abramowsky",
    "email": "vabramowsky10@jugem.jp",
    "createdAt": "2019-06-11"
  }, {
    "id": 38,
    "nome": "Bud",
    "sobrenome": "O' Brian",
    "email": "bobrian11@creativecommons.org",
    "createdAt": "2019-03-19"
  }, {
    "id": 39,
    "nome": "Donielle",
    "sobrenome": "Chalfain",
    "email": "dchalfain12@amazonaws.com",
    "createdAt": "2019-02-09"
  }, {
    "id": 40,
    "nome": "Rikki",
    "sobrenome": "Jeayes",
    "email": "rjeayes13@github.com",
    "createdAt": "2018-11-29"
  }, {
    "id": 41,
    "nome": "Cherrita",
    "sobrenome": "Armell",
    "email": "carmell14@salon.com",
    "createdAt": "2018-12-21"
  }, {
    "id": 42,
    "nome": "Ginelle",
    "sobrenome": "Peppin",
    "email": "gpeppin15@bizjournals.com",
    "createdAt": "2019-11-13"
  }, {
    "id": 43,
    "nome": "Olympia",
    "sobrenome": "Ketteridge",
    "email": "oketteridge16@xing.com",
    "createdAt": "2019-01-30"
  }, {
    "id": 44,
    "nome": "Winslow",
    "sobrenome": "Petrovic",
    "email": "wpetrovic17@hatena.ne.jp",
    "createdAt": "2018-11-26"
  }, {
    "id": 45,
    "nome": "Andras",
    "sobrenome": "Cerro",
    "email": "acerro18@who.int",
    "createdAt": "2018-12-14"
  }, {
    "id": 46,
    "nome": "Timmy",
    "sobrenome": "Clerk",
    "email": "tclerk19@house.gov",
    "createdAt": "2019-05-31"
  }, {
    "id": 47,
    "nome": "Ninetta",
    "sobrenome": "Wraggs",
    "email": "nwraggs1a@liveinternet.ru",
    "createdAt": "2019-02-09"
  }, {
    "id": 48,
    "nome": "Danya",
    "sobrenome": "Matzkaitis",
    "email": "dmatzkaitis1b@cbc.ca",
    "createdAt": "2019-11-02"
  }, {
    "id": 49,
    "nome": "Englebert",
    "sobrenome": "Baskeyfied",
    "email": "ebaskeyfied1c@deviantart.com",
    "createdAt": "2019-05-12"
  }, {
    "id": 50,
    "nome": "Janine",
    "sobrenome": "Dotson",
    "email": "jdotson1d@washington.edu",
    "createdAt": "2019-08-01"
  }, {
    "id": 51,
    "nome": "Ara",
    "sobrenome": "Locker",
    "email": "alocker1e@reference.com",
    "createdAt": "2019-07-27"
  }, {
    "id": 52,
    "nome": "Pippy",
    "sobrenome": "Mapstone",
    "email": "pmapstone1f@arizona.edu",
    "createdAt": "2019-01-10"
  }, {
    "id": 53,
    "nome": "Cart",
    "sobrenome": "Tzar",
    "email": "ctzar1g@wikispaces.com",
    "createdAt": "2019-08-29"
  }, {
    "id": 54,
    "nome": "Imogene",
    "sobrenome": "Aucourte",
    "email": "iaucourte1h@china.com.cn",
    "createdAt": "2019-09-11"
  }, {
    "id": 55,
    "nome": "Tildi",
    "sobrenome": "Lloyds",
    "email": "tlloyds1i@china.com.cn",
    "createdAt": "2019-03-29"
  }, {
    "id": 56,
    "nome": "Linc",
    "sobrenome": "Lachaize",
    "email": "llachaize1j@privacy.gov.au",
    "createdAt": "2019-05-25"
  }, {
    "id": 57,
    "nome": "Muffin",
    "sobrenome": "Etteridge",
    "email": "metteridge1k@amazon.de",
    "createdAt": "2019-10-28"
  }, {
    "id": 58,
    "nome": "Jakie",
    "sobrenome": "Newcome",
    "email": "jnewcome1l@blogs.com",
    "createdAt": "2019-09-10"
  }, {
    "id": 59,
    "nome": "Maurene",
    "sobrenome": "Bone",
    "email": "mbone1m@archive.org",
    "createdAt": "2019-05-20"
  }, {
    "id": 60,
    "nome": "Geoffrey",
    "sobrenome": "Lorenz",
    "email": "glorenz1n@opera.com",
    "createdAt": "2019-08-20"
  }, {
    "id": 61,
    "nome": "Bettye",
    "sobrenome": "Skaid",
    "email": "bskaid1o@sciencedaily.com",
    "createdAt": "2019-09-01"
  }, {
    "id": 62,
    "nome": "Saunder",
    "sobrenome": "Dumper",
    "email": "sdumper1p@dailymail.co.uk",
    "createdAt": "2018-12-09"
  }, {
    "id": 63,
    "nome": "Dalt",
    "sobrenome": "Strapp",
    "email": "dstrapp1q@fema.gov",
    "createdAt": "2019-10-25"
  }, {
    "id": 64,
    "nome": "Ford",
    "sobrenome": "Whiteman",
    "email": "fwhiteman1r@unc.edu",
    "createdAt": "2018-12-16"
  }, {
    "id": 65,
    "nome": "Nicholas",
    "sobrenome": "MacCorkell",
    "email": "nmaccorkell1s@comsenz.com",
    "createdAt": "2019-11-07"
  }, {
    "id": 66,
    "nome": "Ora",
    "sobrenome": "MacNess",
    "email": "omacness1t@domainmarket.com",
    "createdAt": "2019-06-03"
  }, {
    "id": 67,
    "nome": "Pren",
    "sobrenome": "Moneti",
    "email": "pmoneti1u@patch.com",
    "createdAt": "2019-08-09"
  }, {
    "id": 68,
    "nome": "Dennis",
    "sobrenome": "Miguet",
    "email": "dmiguet1v@sphinn.com",
    "createdAt": "2019-07-23"
  }, {
    "id": 69,
    "nome": "Sallyann",
    "sobrenome": "Cottrill",
    "email": "scottrill1w@constantcontact.com",
    "createdAt": "2019-07-25"
  }, {
    "id": 70,
    "nome": "Alex",
    "sobrenome": "Hasell",
    "email": "ahasell1x@xinhuanet.com",
    "createdAt": "2018-12-15"
  }, {
    "id": 71,
    "nome": "West",
    "sobrenome": "Copozio",
    "email": "wcopozio1y@bizjournals.com",
    "createdAt": "2019-01-30"
  }, {
    "id": 72,
    "nome": "Cale",
    "sobrenome": "Shirtcliffe",
    "email": "cshirtcliffe1z@uiuc.edu",
    "createdAt": "2019-05-14"
  }, {
    "id": 73,
    "nome": "Mercie",
    "sobrenome": "Dalzell",
    "email": "mdalzell20@independent.co.uk",
    "createdAt": "2019-02-18"
  }, {
    "id": 74,
    "nome": "Meriel",
    "sobrenome": "Casiroli",
    "email": "mcasiroli21@xing.com",
    "createdAt": "2019-01-21"
  }, {
    "id": 75,
    "nome": "Archibaldo",
    "sobrenome": "Vallentin",
    "email": "avallentin22@yellowbook.com",
    "createdAt": "2019-09-30"
  }, {
    "id": 76,
    "nome": "Biddy",
    "sobrenome": "Allnatt",
    "email": "ballnatt23@hud.gov",
    "createdAt": "2019-02-26"
  }, {
    "id": 77,
    "nome": "Bentley",
    "sobrenome": "Fibbit",
    "email": "bfibbit24@tripod.com",
    "createdAt": "2019-04-02"
  }, {
    "id": 78,
    "nome": "Marielle",
    "sobrenome": "Mungin",
    "email": "mmungin25@cisco.com",
    "createdAt": "2019-07-10"
  }, {
    "id": 79,
    "nome": "Gabriele",
    "sobrenome": "Hoopper",
    "email": "ghoopper26@cnbc.com",
    "createdAt": "2019-08-13"
  }, {
    "id": 80,
    "nome": "Martita",
    "sobrenome": "Lamzed",
    "email": "mlamzed27@yelp.com",
    "createdAt": "2019-07-09"
  }, {
    "id": 81,
    "nome": "Nerti",
    "sobrenome": "Gibke",
    "email": "ngibke28@gizmodo.com",
    "createdAt": "2019-04-09"
  }, {
    "id": 82,
    "nome": "Agace",
    "sobrenome": "Pendlenton",
    "email": "apendlenton29@bloglines.com",
    "createdAt": "2019-11-10"
  }, {
    "id": 83,
    "nome": "Vonnie",
    "sobrenome": "Landsberg",
    "email": "vlandsberg2a@apple.com",
    "createdAt": "2019-11-11"
  }, {
    "id": 84,
    "nome": "Latia",
    "sobrenome": "Statefield",
    "email": "lstatefield2b@tripadvisor.com",
    "createdAt": "2019-05-09"
  }, {
    "id": 85,
    "nome": "Hanny",
    "sobrenome": "Virgo",
    "email": "hvirgo2c@de.vu",
    "createdAt": "2019-05-03"
  }, {
    "id": 86,
    "nome": "Orly",
    "sobrenome": "Ritelli",
    "email": "oritelli2d@blogs.com",
    "createdAt": "2019-03-14"
  }, {
    "id": 87,
    "nome": "Roosevelt",
    "sobrenome": "Shafe",
    "email": "rshafe2e@a8.net",
    "createdAt": "2018-12-20"
  }, {
    "id": 88,
    "nome": "Trenna",
    "sobrenome": "Serris",
    "email": "tserris2f@networkadvertising.org",
    "createdAt": "2019-09-12"
  }, {
    "id": 89,
    "nome": "Kennie",
    "sobrenome": "Potebury",
    "email": "kpotebury2g@mail.ru",
    "createdAt": "2019-01-16"
  }, {
    "id": 90,
    "nome": "Rustin",
    "sobrenome": "Solway",
    "email": "rsolway2h@accuweather.com",
    "createdAt": "2019-06-12"
  }, {
    "id": 91,
    "nome": "Korella",
    "sobrenome": "Dorgon",
    "email": "kdorgon2i@census.gov",
    "createdAt": "2019-03-18"
  }, {
    "id": 92,
    "nome": "Karalynn",
    "sobrenome": "Middlemist",
    "email": "kmiddlemist2j@1688.com",
    "createdAt": "2019-07-08"
  }, {
    "id": 93,
    "nome": "Stu",
    "sobrenome": "Middas",
    "email": "smiddas2k@csmonitor.com",
    "createdAt": "2019-08-31"
  }, {
    "id": 94,
    "nome": "Carmita",
    "sobrenome": "Senn",
    "email": "csenn2l@creativecommons.org",
    "createdAt": "2019-04-19"
  }, {
    "id": 95,
    "nome": "Pinchas",
    "sobrenome": "Fetherston",
    "email": "pfetherston2m@cnbc.com",
    "createdAt": "2019-03-16"
  }, {
    "id": 96,
    "nome": "Layla",
    "sobrenome": "Myner",
    "email": "lmyner2n@webnode.com",
    "createdAt": "2018-12-27"
  }, {
    "id": 97,
    "nome": "Marcie",
    "sobrenome": "Gealy",
    "email": "mgealy2o@g.co",
    "createdAt": "2019-07-16"
  }, {
    "id": 98,
    "nome": "Legra",
    "sobrenome": "Franssen",
    "email": "lfranssen2p@admin.ch",
    "createdAt": "2019-06-07"
  }, {
    "id": 99,
    "nome": "Cassandra",
    "sobrenome": "Irvin",
    "email": "cirvin2q@cmu.edu",
    "createdAt": "2019-08-01"
  }, {
    "id": 100,
    "nome": "Vitoria",
    "sobrenome": "Simeoli",
    "email": "vsimeoli2r@typepad.com",
    "createdAt": "2019-04-19"
  }];

  constructor() { }

  ngOnInit() {
  }

}
